#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

cd "$(dirname "${BASH_SOURCE[0]}")/.."

PROJECT_REF="lvcbmopdstvupjpytjbb"
FUNCTIONS_BASE="https://${PROJECT_REF}.supabase.co/functions/v1"
DASH="https://supabase.com/dashboard/project/${PROJECT_REF}"

# Secrets land here, never in git (.gitignore covers .env*). Re-running the
# wizard reuses what is already in this file rather than rotating secrets that
# are now pinned in two places each.
ENV_FILE=".env.notify"

# ensure_secret KEY: reuse the value already in ENV_FILE, or mint a new one.
ensure_secret() {
  local key="$1" current
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf -v "$key" '%s' "$current"
    note "$key already set, keeping it"
  else
    printf -v "$key" '%s' "$(openssl rand -hex 32)"
    write_env "$key" "${!key}"
  fi
}

TOTAL_STAGES=8

banner "Telegram guardian notifications"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Supabase CLI: install, log in, link"
say "The two Edge Functions are deployed with the Supabase CLI."
if command -v supabase >/dev/null 2>&1; then
  note "supabase $(supabase --version 2>/dev/null || echo '?') already installed"
else
  step "Not installed. Installing with Homebrew (a few minutes)."
  if confirm "Run 'brew install supabase' now?"; then
    brew install supabase
  else
    warn "Install it yourself, then re-run this wizard."
    exit 1
  fi
fi

if supabase projects list >/dev/null 2>&1; then
  note "already logged in"
else
  step "A browser window will open. Approve the login, then come back."
  supabase login
fi

if [[ -f supabase/.temp/project-ref ]]; then
  note "project already linked"
else
  step "Linking to project ${PROJECT_REF}."
  warn "This asks for your DATABASE password (not your account password)."
  note "Forgotten it? Reset at ${DASH}/settings/database"
  supabase link --project-ref "$PROJECT_REF"
fi
pause "Linked. Press Enter."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Telegram: create the bot"
say "BotFather is a chat, not a web page. It opens in the Telegram app."
open_url "https://t.me/BotFather"
step "Send:  /newbot"
step "Display name — what parents see. e.g.  MVTS Gate"
step "Username — must be unique and end in 'bot'. e.g.  mvts_gate_bot"
step "BotFather replies with a token like  8123456789:AAH-xxxxxxxxxxxxxxxxxxxxx"
warn "That token is the whole bot. Anyone holding it can message every parent."
ask_secret TELEGRAM_BOT_TOKEN "Paste the bot token:"
ask TELEGRAM_BOT_USERNAME "Bot username (without the @):"
TELEGRAM_BOT_USERNAME="${TELEGRAM_BOT_USERNAME#@}"
write_env TELEGRAM_BOT_TOKEN "$TELEGRAM_BOT_TOKEN"
write_env TELEGRAM_BOT_USERNAME "$TELEGRAM_BOT_USERNAME"

step "Checking the token with Telegram..."
if curl -sS "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/getMe" | grep -q '"ok":true'; then
  printf '  %s✓%s Telegram accepted the token\n' "$GREEN" "$RESET"
else
  warn "Telegram rejected that token. Check for a stray space and re-run."
  exit 1
fi
pause "Press Enter."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Shared secrets"
say "Two secrets, each of which must match in two places:"
note "  WEBHOOK_SECRET          Supabase secrets  +  the trigger in sql/webhook.sql"
note "  TELEGRAM_WEBHOOK_SECRET Supabase secrets  +  Telegram's setWebhook call"
say ""
say "Generating them here so both halves are guaranteed to agree."
ensure_secret WEBHOOK_SECRET
ensure_secret TELEGRAM_WEBHOOK_SECRET
ask SCHOOL_NAME "School name as parents should see it (e.g. Mabini High School):"
write_env SCHOOL_NAME "$SCHOOL_NAME"

step "Uploading to Supabase..."
supabase secrets set \
  "TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}" \
  "WEBHOOK_SECRET=${WEBHOOK_SECRET}" \
  "TELEGRAM_WEBHOOK_SECRET=${TELEGRAM_WEBHOOK_SECRET}" \
  "SCHOOL_NAME=${SCHOOL_NAME}" \
  "SCHOOL_TZ=Asia/Manila"
pause "Secrets set. Press Enter."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Deploy the Edge Functions"
say "notify-guardian  — fans one scan out to that student's guardians"
say "telegram-webhook — guardian enrolment via the /start deep link"
note "--no-verify-jwt because each authenticates with its own shared secret:"
note "Telegram never sends a Supabase JWT, and neither does the pg_net trigger."
supabase functions deploy notify-guardian  --no-verify-jwt
supabase functions deploy telegram-webhook --no-verify-jwt
pause "Both deployed. Press Enter."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Point Telegram at the bot webhook"
say "This tells Telegram where to deliver messages parents send the bot."
resp=$(curl -sS -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/setWebhook" \
  -H 'Content-Type: application/json' \
  -d "{\"url\":\"${FUNCTIONS_BASE}/telegram-webhook\",
       \"secret_token\":\"${TELEGRAM_WEBHOOK_SECRET}\",
       \"allowed_updates\":[\"message\"]}" || true)
if grep -q '"ok":true' <<<"$resp"; then
  printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$resp"
else
  warn "setWebhook failed:"; say "$resp"; exit 1
fi
pause "Press Enter."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Install the attendance trigger"
say "This is the trigger that fires notify-guardian on every new scan."
say "It lives in sql/webhook.sql rather than in the Studio webhook form, so"
say "it is version-controlled and does not depend on where Supabase last"
say "moved that page."
open_url "${DASH}/sql/new"
step "Open sql/webhook.sql, replace PASTE_WEBHOOK_SECRET_HERE with:"
say ""
note "  ${WEBHOOK_SECRET}"
say ""
step "Paste the whole file into the SQL editor and run it."
warn "Copy that secret exactly. A mismatch shows up as 403s in the function"
warn "logs, not as an error anywhere you are looking."
note "It also drops the old mvts_esp32 trigger if that schema is still around,"
note "so nobody gets messaged twice during the cutover."
pause "Trigger installed? Press Enter."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Link yourself as a test guardian"
say "A bot cannot message you until you have messaged it, so link your own"
say "Telegram to a student first."
say ""
say "The roster is PTA Collections', so pick a real student who already holds"
say "a card. Enrol one on /enroll first if none do."
open_url "${DASH}/sql/new"
step "Find a student with a card, and note their CARD UID:"
say ""
note "  select r.student_id, r.full_name, r.student_no, c.card_uid"
note "    from pta.gate_roster r"
note "    join pta.student_cards c"
note "      on c.student_id = r.student_id and c.revoked_at is null"
note "   limit 10;"
say ""
ask TEST_CARD_UID "Paste the card_uid you will test with:"
write_env TEST_CARD_UID "$TEST_CARD_UID"
step "Now issue an enrolment token for that student:"
say ""
note "  select pta.issue_enroll_token("
note "    (select student_id from pta.gate_roster r"
note "       join pta.student_cards c on c.student_id = r.student_id"
note "      where c.card_uid = '"'"'${TEST_CARD_UID}'"'"' and c.revoked_at is null));"
say ""
step "Copy the 32-character token it returns."
ask ENROLL_TOKEN "Paste the token:"
step "Opening the deep link a parent would get as a QR code..."
open_url "https://t.me/${TELEGRAM_BOT_USERNAME}?start=${ENROLL_TOKEN}"
step "Press START in Telegram."
say ""
say "Expect: 'You are now linked to <the student you picked>.'"
note "Nothing at all? The bot webhook is wrong — check stage 5."
note "'That link was not recognised'? The token was truncated on paste."
pause "Linked? Press Enter."

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "End-to-end test"
say "Fake a gate scan for that card, exactly as the device would post it."
open_url "${DASH}/sql/new"
step "Run this:"
say ""
note "  select pta.record_attendance(jsonb_build_array("
note "    jsonb_build_object("
note "      'event_id',     gen_random_uuid()::text,"
note "      'card_uid',     '${TEST_CARD_UID}',"
note "      'device_id',    'gate-01',"
note "      'scanned_at',   now()::text,"
note "      'clock_synced', true)));"
say ""
say "Within a few seconds Telegram should say that student passed the gate."
note "No photo yet — the camera is not wired up, and the notifier falls back"
note "to a text message when image_path is null. That is the designed path."
say ""
warn "Nothing arrived? Check, in this order:"
note "  select event_id, status, delivery_class, attempts, error"
note "    from pta.gate_notifications order by created_at desc limit 5;"
note ""
note "  no rows        → the trigger never fired (stage 6), or the scan"
note "                   resolved to no student — the card is unassigned"
note "  status failed  → read 'error'; 403 means the secret does not match"
note "  status sent    → it worked; check the right Telegram account"
note ""
note "'unregistered or inactive gate device'? gate-01 is not in"
note "pta.gate_devices. Run sql/cutover.sql."
note ""
note "Function logs: ${DASH}/functions/notify-guardian/logs"
pause "Press Enter for the summary."

finish
say "Bot:        @${TELEGRAM_BOT_USERNAME}"
say "Secrets:    .env.notify  (gitignored — keep it, re-runs reuse it)"
say ""
say "To enrol a real guardian, issue a token for their child and print"
say "https://t.me/${TELEGRAM_BOT_USERNAME}?start=<token> as a QR on the slip."
printf '\n'
